/*
 * Softplan JurosCompostos
 *
 * Swagger para aplicação JurosCompostos da SoftPlan.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: matheus.linorp@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using NSwag.Annotations;

namespace JurosCompostos.Controllers
{ 
    /// <summary>
    /// Serviço para retornar a url do projeto no github
    /// </summary>
    public class ShowMeTheCodeApiController : Controller
    { 
        /// <summary>
        /// Retorna a url do projeto no github
        /// </summary>        
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/showmethecode")]
        [ValidateModelState]
        [SwaggerOperation("Showmethecode")]
        public virtual IActionResult ShowMeTheCode()
        {
            return Ok("http://google.com");
        }
    }
}
